events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    
    # --- UPSTREAMS ---
    upstream grafana         { server grafana_dashboard:3000; }
    upstream prometheus      { server prometheus_server:9090; }
    upstream api             { server pr007-api-1:8000; }

    server {
        # Écoute HTTP standard
        listen 80;
        # Écoute HTTPS
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/CA.crt;
        ssl_certificate_key /etc/nginx/certs/CA.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        # Route Grafana
        location /grafana/ {
            # Décommenter si l'auth fonctionne
            # include /etc/nginx/auth.conf; 
            
            proxy_pass http://grafana; 
            include proxy_headers.conf;
        }

        # Route Prometheus
        location /prometheus/ {
            proxy_pass http://prometheus_server:9090/prometheus/;

            # Ajoute ces lignes pour éviter les coupures (timeout)
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;

            # Important pour les websockets et requêtes persistantes (ce qui causait ton erreur 499)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;

            include proxy_headers.conf;
        }
    }
}