stages:

  mergInc:
    #différente forme d'appelle
    #cmd:  python -c "import sys; from src.collect import merge_avis; merge_avis(sys.argv[1])" params.yaml
    #cmd:  python -c "from src.collect import merge_avis; merge_avis('params.yaml')" 
    cmd:  python -c "from src.collect import merge_avis; merge_avis()" 
    deps:
      - params.yaml
      - src/collect.py
      - data/avis_40k.csv
      - data/avis_28k.csv
    outs:
      - data/avis_45k.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/avis_40k.csv
    outs:
      - data/avis_cleaned.csv

  nlp_simple:
    cmd: python src/preprocess_nlp.py
    deps:
      - src/preprocess_nlp.py
      - data/avis_cleaned.csv
    outs:
      - data/avis_nlp.csv

  spacy_lemmatization:
    cmd: python src/preprocess_spacy.py
    deps:
      - src/preprocess_spacy.py
      - data/avis_cleaned.csv
    outs:
      - data/avis_bertopic.csv

  train:
    #cmd: bash -c 'python src/train.py --filepath data/avis_bertopic.csv --model_output models/BERTopic  $TRAIN_ARGS'
    cmd: python src/train.py --filepath data/avis_bertopic.csv --model_output models/BERTopic $TRAIN_ARGS
    deps:
      - src/train.py
      - data/avis_bertopic.csv
    outs:
      - models/BERTopic
      - models/BERTopic_kmeans.pkl
      - models/BERTopic_meta_labels.pkl
      - models/BERTopic_topic_to_meta.pkl
      - models/BERTopic_embeddings.pkl
      - data/clusterized.csv
  
  evaluate:
    cmd: python src/evaluate.py --filepath data/clusterized.csv --metrics_output metrics/silhouette.json
    deps:
      - src/evaluate.py
      - data/clusterized.csv
    metrics:
      - metrics/silhouette.json
