collect:
  source: "avis_45k"
  mode: "bulk"            # "incremental" ou "bulk" ou "predict" attention 
  period_sta: "P202401"   # en incremental : juste les nouveaux sont ajoutés, en predict on batch qu'un petit bout
  period_end: "P202603"
