    #global:
      # scrape_interval: 10s
    
    #plusieurs configs possible
    scrape_configs:
      #config de relevé de metrics machine sur l'api ngincx_exporter
      - job_name: 'nginx-exporter'
        scrape_interval: 10s
        static_configs:
          - targets: ['nginx_exporter:9113']
    
     # Scrape API : silhouette score - ne sert à rien encore ici on scrape une constante
      #config de metric machine sur l'api de
      - job_name: "api"
        scrape_interval: 5s
        static_configs:
         - targets: ["pr007-api-1:8000"]
        metrics_path: /metrics_prom  # endpoint exposé par FastAPI pour Prometheus

      - job_name: "pushgateway"       
        scrape_interval: 3s
        static_configs:
          - targets: ["pushgateway:9091"]
        honor_labels: true             # on garde les labels du push 

     # pour des collections ponctuelle -> push après le train, voir la config pushgateway, mais qui ajoute un docker à la troupe
     # pour recharger ce fichier de config soit:
     #  1/ ```docker compose -p pr001 -f docker-compose1.yaml up -d prometheus```
     #  2/ ```docker exec prometheus_server curl -X POST http://localhost:9090/-/reload```
     #  3/ si curl est pas là -> vérif os-release  ```docker exec nginx_revproxy cat /etc/os-release```
     #     puis insall alpin ou debian de curl, wget, nslookup (via resp bind-tools ou dnsutils) ping(iputils ou iputils-ping, nc(netcat-openbsd))