#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""train.py:
Train the model, generate 10 final clusters, export data_clusterized.csv, model, metrics and logs.

AUTHOR
Robin Mom

VERSION
1.0

DATE
29/04/2026
"""
### Imports

import argparse
import logging as log # module standard pour la gestion des messages de diagnostic.
import joblib
import pandas as pd
import numpy as np
import ast
import json
from sklearn.metrics import silhouette_score

### MAIN

def main(verbose, filepath, sep, col_topics, col_embs, metrics_output, log_output):

	# -------------------------
	# 1. Chargement des données
	# -------------------------
	log.info(f"loading clusterized data {filepath}")
	df = pd.read_csv(filepath)
	with open(log_output, "w", encoding="utf-8") as f:
		f.write(f"loading clusterized data {filepath}")
	# -------------------------
	# 2. Préparation
	# -------------------------
	# On enlève les outliers (-1)
	mask = df[col_topics] != -1

	X = np.vstack(
		df.loc[mask, col_embs]
		.apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))
		.values
	)
	labels = df.loc[mask, col_topics].values

	# -------------------------
	# 3. Silhouette score
	# -------------------------
	if len(set(labels)) > 1:
		score = silhouette_score(X, labels, metric="cosine")
		
		log.info(f"Silhouette score (cosine): {score:.4f}")
		with open(log_output, "a", encoding="utf-8") as f:
			f.write(f"Silhouette score (cosine): {score:.4f}")
		metrics = {
			"silhouette_score": float(score)  # conversion importante (numpy -> float)
		}

		with open(metrics_output, "w", encoding="utf-8") as f:
			json.dump(metrics, f, indent=4)

		log.info(f"Metrics saved to {metrics_output}")
		with open(log_output, "a", encoding="utf-8") as f:
			f.write(f"Metrics saved to {metrics_output}")

	else:
		log.info("Impossible de calculer le silhouette score (1 seul cluster)")
		with open(log_output, "a", encoding="utf-8") as f:
			f.write("Impossible de calculer le silhouette score (1 seul cluster)")

def _cli():
    parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            argument_default=argparse.SUPPRESS)
    parser.add_argument('-v', '--verbose', action='store_true', default=False, help="Boolean: activate verbose mode. Default is no verbose.")
    parser.add_argument('-f', '--filepath', default="data/clusterized.csv", type=str, help="path to your input csv file of clusterized dataset generated by train.py")
    parser.add_argument('-s', '--sep', default=',', type=str, help="separator to parse input csv")
    parser.add_argument('-ct', '--col_topics', default="meta_topic", type=str, help="Column name in clusterized data dataframe to use for topics assignement")
    parser.add_argument('-ce', '--col_embs', default="embedding", type=str, help="Column name in clusterized data dataframe to use for embeddings assignement")
    parser.add_argument('-Mo', '--metrics_output', default="metrics/silhouette.json", type=str, help="Name of output file for silhouette score metric")
    parser.add_argument('-lo', '--log_output', default="models/minimal.log", type=str, help="Name of output file for minimal logs.")
        
    args = parser.parse_args()
    
    if args.verbose == True :
        log.basicConfig(format="%(levelname)s: %(message)s", level=log.DEBUG)
        log.info("Verbose output.")
    else:
        log.basicConfig(format="%(levelname)s: %(message)s")

    return vars(args)

if __name__ == '__main__':
    main(**_cli())












