services:
  # Service 1 : L'API (Inférence) Oscaro Trust Pilot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-mlopsv}-app          # ← nomme et tag l'image buildée, COMPOSE_PROJECT_NAME vient de -p
    ports:
      - "8000:8000"
    volumes:
      - ../../.:/app # Permet de voir les modifs de code en temps réel (développement)
      - /app/.venv
    env_file:
      - ../../.env
    networks:
      - airflow_default  # ✅ référence uniquement
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]

  # Service 2 : Le Trainer (Cycle de vie ML)
  trainer:
    image: ${COMPOSE_PROJECT_NAME:-mlopsv}-app          # ← réutilise l'image buildée par api
    profiles:
      - training               # ← exclu du up classique ✅
    volumes:
      - ../../.:/app
    env_file:
      - ../../.env
    # Ce container s'éteint tout seul une fois l'entraînement fini
    command: ["dvc", "repro", "--force"]

# Démarrage normal — trainer ignoré
#docker compose up -d
# Lancer trainer manuellement si besoin et voir les trois options de lancement via dags ou mlflow 
#docker compose --profile training run --rm trainer


# app/docker-compose.yaml — rejoindre le réseau
#networks:
#  airflow_default:
#    external: true               # réseau déjà créé par la stack Airflow
