services:
  # Service 1 : L'API (Inférence) Oscaro Trust Pilot
  common:
    build:
      context: ../..
      dockerfile: ${DOCKFLD}Dockerfile
      args:
        BACKEND: ${BACKEND:-cpu}
        DOCKFLD: ${DOCKFLD}
        #DAGSHUB_TOKEN: ${DAGSHUB_TOKEN}
    image: ${COMPOSE_PROJECT_NAME:-mlopsv}-app:${API_VERSION:-1.0.0}           # ← nomme et tag l'image buildée, COMPOSE_PROJECT_NAME vient de -p
    profiles:
      - building        # ← exclu du up classique
    command: echo "build only"   # ← ne fait rien, juste pour le build
  
  api:
    image: ${COMPOSE_PROJECT_NAME:-mlopsv}-app:${API_VERSION:-1.0.0}           # ← nomme et tag l'image buildée, COMPOSE_PROJECT_NAME vient de -p
    ports:
      - "8000:8000"
    volumes:
      - ../../.:/app # Permet de voir les modifs de code en temps réel (développement)
      - /app/.venv
    env_file:
      - ../../.env
    #networks:
    #  - airflow_default  # ✅ référence uniquement DEBUNK uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s      # vérifie toutes les 5s
      timeout: 3s
      retries: 10        # considère healthy après 5 succès
      start_period: 60s # laisse 30s à l'API pour démarrer

  # Service 2 : Le Trainer (Cycle de vie ML)
  trainer:
    image: ${COMPOSE_PROJECT_NAME:-mlopsv}-app:${API_VERSION:-1.0.0}           # ← réutilise l'image buildée par api
    profiles:
      - training               # ← exclu du up classique ✅
    volumes:
      - ../../.:/app
    env_file:
      - ../../.env
    # Ce container s'éteint tout seul une fois l'entraînement fini
    command: ["dvc", "repro", "--force"]

# Démarrage normal — trainer ignoré
#docker compose up -d
# Lancer trainer manuellement si besoin et voir les trois options de lancement via dags ou mlflow 
#docker compose --profile training run --rm trainer


# app/docker-compose.yaml — rejoindre le réseau
networks:
  airflow_default:
    external: true               # réseau déjà créé par la stack Airflow
    name: airflow_default