name: Supply Chain MLOps CI

on:
  push:
    branches: [ main, feat/ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu Runner)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/lib/jvm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check environnement
        run: |
          pwd
          ls -arl
          df -Ph
          free -h
          hostname
          which git
          echo $PATH
           grep -a2 "last_run_id" dvc.lock|grep md5:


      - name: Create .env file for Docker Compose
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/schmilblick-ai/Supply-Chain-MLOps.mlflow" >> .env
          echo "MLFLOW_TRACKING_USERNAME=marv1-ops" >> .env
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> .env
          echo "DAGSHUB_CLIENT_TOKEN=${{ secrets.DAGSHUB_CLIENT_TOKEN }}" >> .env

      - name: Create dummy external network for Airflow
        run: docker network create airflow_default || true

      # 🔐 CONFIGURATION ET PULL DVC AMÉLIORÉE
      # On injecte les secrets directement dans l'environnement du conteneur
      - name: Pull Data and Models from DVC
        run: |
          docker compose run --rm \
            -e DAGSHUB_TOKEN="${{ secrets.DAGSHUB_CLIENT_TOKEN }}" \
            trainer sh -c "
              #dvc init --no-scm --force
              cd /app
              dvc remote add -d origin https://dagshub.com/schmilblick-ai/Supply-Chain-MLOps.dvc
              dvc remote modify origin auth basic
              dvc remote modify origin user marv1-ops
              dvc remote modify origin password \$DAGSHUB_TOKEN
              dvc pull -r origin
            "

      - name: Run unit tests via Docker
        run: |
          docker compose run --rm trainer pytest tests/

      - name: Build API Docker image
        run: |
          docker compose build api