name: Supply Chain MLOps CI

on:
  push:
    branches: [ main, feat/ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu Runner)
        run: |
          whoami
          id runner && true
          which curl
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/lib/jvm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check environnement et PULL DVC sur la vm - séparation des responsabilités
        if: true
        run: |
          pwd ; ls -arl ; df -Ph ; free -h ; hostname ; which git
          echo $PATH ; docker ps || true
          pip install dvc[http]
          dvc remote add -d --force origin https://dagshub.com/schmilblick-ai/Supply-Chain-MLOps.dvc
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user marv1-ops
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_CLIENT_TOKEN }}
          dvc pull -r origin

      - name: Create .env file for Docker Compose
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/schmilblick-ai/Supply-Chain-MLOps.mlflow" >> .env
          echo "MLFLOW_TRACKING_USERNAME=marv1-ops" >> .env
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> .env
          echo "export DAGSHUB_CLIENT_TOKEN=${{ secrets.DAGSHUB_CLIENT_TOKEN }}" >> .env
          echo "export DAGSHUB_USER_TOKEN=${{ secrets.DAGSHUB_CLIENT_TOKEN }}" >> .env

      - name: Create dummy external network for Airflow
        run: docker network create airflow_default || true

      - name: Build et start API Docker image
        run: |
          docker compose up -d api
          docker ps
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_CLIENT_TOKEN }}

      - name: Check API logs
        run: |
          docker ps
          docker system df
          docker compose logs api


      - name: open trainer and check dvc status avec synchro docker
        run: |
          docker compose run --rm \
            trainer sh -c "
              cd /app
              ls -arl .dvc
              dvc pull -r origin
              dvc status -r origin
            "
      - name: Wait for API
        run: |
          until curl -sf http://localhost:8000/health; do
            sleep 3
          done

      - name: Run unit tests depuis la vm - Après la synchro - api dispo
        run: |
          pip install pytest requests
          pytest tests/
