name: Supply CI 1 image for 2 container

on:
  workflow_dispatch:    # ← tu contrôles manuellement
  push:
    branches: [ feat/nginx_2 ]   # ← ou sur ta branche de dev

env:
  BACKEND: cpu                  #cpu ou gpu
  DOCKFLD: dockers/slim/        #${DOCKFLD}
  COMPOSE_PROJECT_NAME: pr142 
  API_VERSION: 0.0
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_CLIENT_TOKEN }}

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-142
          key: ${{ runner.os }}-docker-${{ hashFiles('${DOCKFLD}/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      # Un seul build — les deux services l'utilisent
      - name: Build img142
        run: | 
          docker compose -f ${DOCKFLD}/docker-compose.yaml build common
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull data
        run: |
          pip install dvc[http]
          dvc remote add -d --force origin https://dagshub.com/schmilblick-ai/Supply-Chain-MLOps.dvc
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user marv1-ops
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_CLIENT_TOKEN }}
          dvc pull -r origin

      - name: Start API
        run: 
          docker compose -p $(PROJECT) -f ${DOCKFLD}/docker-compose.yaml up -d api 

      - name: Run tests
        run: docker compose -p $(PROJECT) -f ${DOCKFLD}/docker-compose.yaml run --rm trainer pytest tests/
